### PR TITLE
added aside section, styled the thumnails and finished it

### PR DESCRIPTION
**Pull request by Osong-Michael**

### CODE REVIEW

**Comment by Osong-Michael** [comment]
Most of the changes have been done on the Osong branch, but for some reason unkown to us the font awesome icons don't display in the live demo, also the live demo is reflecting the master branch, so it looks incomplete.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @OA7 and @Samitti 
### Good job for the work done so far :clap: However, you have a few changes to work on before your project could be approved.
- You can use font-awesome to display the your icons, [check this guide](https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use)
icons
- Validate your html code and solve the errors displayed, [use this website](https://validator.w3.org/#validate-by-upload)
validate
- On your sidebar, use video thumbnails and make the background uniform to page background
video thumbnails
- Your content needs to be centered, meaning having an equal margin on the left and right 
left-margin
- The like, share buttons make them go o the right as in the original design
go-right

### Make these changes and resubmit for another code review. Good luck.
- For assistance, contact me on @rOluochKe
- Happy coding!

**Comment by Samitti** [comment]
Font awesome icons fixed.
Sections have been centralized.
HTML has been validated.

**Review by euqueme — APPROVED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @OA7 and @Samitti  :balloon: :lollipop: 

### Thank you for doing the changes required by the previous reviewer, :medal_sports:  your project looks good enough and that's why I have no choice but to approve it :heavy_check_mark: 

### I have some suggestions for you though so if you decide to do them you don't have to submit for a code review again since this project is approved :point_down: 

### Page structure

**Navbar**

- [ ] the search bar should be more centered in the page and the icons at the right should be closer together like the original

- Yours

image

- Original

image

**Video and Sidebar size**

- [ ] the Video should be bigger and the video thumbnails should be smaller like the original

- Yours

image

- Original

image

**Subscribe button and like and dislike links**

- [ ] Use the `<button>` tag for the SUBSCRIBE button below the video, also the like and dislike icons should be surrounded by `<a>` tags

## Optional

- [ ] [OPTIONAL] I encourage the use of `<nav>` tag for the main navigation links of a page (on the top for this page)
- [ ] [OPTIONAL] your Live Demo leads to a page not found, please consider fixing it or remove it from your Readme file

### That's it, team! :raised_hands: 

### Please make the changes (or not) but if you do, don't forget to check for HTML errors :memo: after you are done and submit a project completion form because as I said, your project has been approved! :rocket: 
Happy coding! :woman_technologist: 

PROJECT STATUS: APPROVED :green_apple:

**Pull request merged**
